# Regenerates ../erd_data.h from graph_anon.json. Committed alongside its output so the header
# is reproducible without the source model:  python3 gen_data.py > ../erd_data.h
import json

g = json.load(open('graph_anon.json'))
cur, added = g['cur'], set(g['added'])
frozen = sorted(n for n in cur['figs'] if n not in added)
new = sorted(added)
order = frozen + new
idx = {n: i for i, n in enumerate(order)}

W = max(f[0] + f[2] for f in cur['figs'].values()) + 40
H = max(f[1] + f[3] for f in cur['figs'].values()) + 40

print('/* erd_data.h -- the anonymized production schema from data/graph_anon.json.')
print(' * GENERATED by data/gen_data.py; edit that and regenerate, never this.')
print(' * Frozen tables first, then the %d the migration added. Coordinates are centres' % len(new))
print(' * from the human-accepted layout; for the added tables they are the human\'s answer,')
print(' * scored as a reference and never given to the search. */')
print('#define ERD_NFIXED %d' % len(frozen))
print('#define ERD_NNEW   %d' % len(new))
print('#define ERD_NEDGE  %d' % len(cur['edges']))
print('#define ERD_CW     %g' % W)
print('#define ERD_CH     %g' % H)
print('static const char *const erd_name[%d] = {' % len(order))
for i in range(0, len(order), 10):
    print('    ' + ' '.join('"%s",' % n for n in order[i:i+10]))
print('};')
for arr, j in (('cx', 0), ('cy', 1)):
    v = ['%g' % (cur['figs'][n][j] + cur['figs'][n][j + 2] / 2) for n in order]
    print('static const double erd_%s[%d] = {' % (arr, len(order)))
    for i in range(0, len(v), 12):
        print('    ' + ', '.join(v[i:i+12]) + ',')
    print('};')
for arr, j in (('w', 2), ('h', 3)):
    v = ['%g' % cur['figs'][n][j] for n in order]
    print('static const double erd_%s[%d] = {' % (arr, len(order)))
    for i in range(0, len(v), 12):
        print('    ' + ', '.join(v[i:i+12]) + ',')
    print('};')
print('static const long erd_edge[%d][2] = {' % len(cur['edges']))
row = ['{%d,%d}' % (idx[a], idx[b]) for a, b in cur['edges']]
for i in range(0, len(row), 8):
    print('    ' + ', '.join(row[i:i+8]) + ',')
print('};')
